# Fichier : codemagic.yaml

workflows:
  ios-app-sideload:
    name: iOS App Build (pour Sideloadly)
    environment:
      xcode: latest
      node: latest
    scripts:
      - name: Installer les dépendances
        script: | 
          npm install
      - name: Construire l'application web
        script: | 
          npm run build
      - name: Synchroniser avec le projet iOS natif
        script: | 
          npx cap sync ios
      - name: Construire l'application (.app) sans signature
        script: | 
          xcodebuild build \
            -workspace "$CM_BUILD_DIR/ios/App/App.xcworkspace" \
            -scheme App \
            -configuration Debug \
            -sdk iphoneos \
            -derivedDataPath "$CM_BUILD_DIR/build/ios/derived_data" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
      - name: Créer le fichier .ipa manuellement
        script: | 
          # On trouve le fichier .app qui vient d'être créé
          APP_PATH=$(find $CM_BUILD_DIR/build/ios/derived_data -name "*.app" | head -n 1)
          
          # On crée le dossier nécessaire
          mkdir -p "$CM_BUILD_DIR/build/ios/ipa/Payload"
          
          # On copie l'application dans ce dossier
          cp -R "$APP_PATH" "$CM_BUILD_DIR/build/ios/ipa/Payload/"
          
          # On se déplace dans le dossier et on compresse pour créer le .ipa
          cd "$CM_BUILD_DIR/build/ios/ipa"
          zip -r "CryptoPayPro.ipa" "Payload"
    artifacts:
      # On dit à Codemagic où trouver le fichier .ipa final
      - build/ios/ipa/*.ipa
