# Placez ce fichier à la racine de votre projet sous le nom : codemagic.yaml

workflows:
  ios-app-build:
    name: Construire l'application iOS
    # --- Configuration de la machine virtuelle (un Mac) ---
    environment:
      node: 20
      xcode: latest
      cocoapods: default
    # --- Scripts à exécuter ---
    scripts:
      - name: Installer les dépendances du projet
        script: npm install

      - name: Construire la version web de l'application
        script: npm run build

      - name: Intégrer Capacitor pour créer le projet iOS
        script: |
          npm install @capacitor/core @capacitor/cli
          # Remplacez "out" par ".next" si votre dossier de build est différent
          npx cap init "CryptoPayPro" "com.cryptopaypro.app" --web-dir "out"
          npx cap add ios

      - name: Installer les dépendances natives (pods)
        script: |
          cd ios/App && pod install

      - name: 🚨 ÉTAPE DE SIGNATURE (BLOQUANTE SANS COMPTE PAYANT) 🚨
        script: |
          # Cette étape initialise le "keychain" de macOS sur le serveur distant.
          keychain initialize
          
          # Ici, Codemagic essaie de récupérer les fichiers .p12 et .mobileprovision
          # que vous êtes censé avoir uploadés dans leurs paramètres.
          # Ces fichiers ne peuvent être obtenus qu'avec un compte développeur PAYANT.
          # SANS CES FICHIERS, LA SUITE ÉCHOUERA.
          keychain add-certificates --certificate "$CM_CERTIFICATE" --certificate-password "$CM_CERTIFICATE_PASSWORD"
          xcode-project use-profiles

      - name: Construire le fichier .ipa
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App"
          
    # --- Où trouver le fichier .ipa une fois la construction terminée ---
    artifacts:
      - build/ios/ipa/*.ipa
